const data = {
  products: [
    {
      id:"1",
      name: "Nike Slim shirt",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/23/737152/1.jpg?1849",
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/03/737152/1.jpg?1788",
      ],

      description: "high qaulity product",
      slug: "nike-slim-shirt",
      price: 190,
      rating: 4.5,
      category: "Nike Shirt",
      brand: "Nike",
      numReviews: 10,
      countInStock: 15,
      colors: ["red", "black", "green"],
    },
    {
      id:"2",
      name: "Adidas Fit Pant",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/23/737152/1.jpg?1849",
        "https://img.joomcdn.net/d1b31b89ab87d5d18006c19fbddabaf73c5c23b9_original.jpeg",
      ],

      description: "good Adidas Slim shirt",
      slug: "addidas-fit-pant",
      price: 140,
      rating: 4.5,
      category: "Pants",
      brand: "Adidas",
      numReviews: 7,
      countInStock: 15,
      colors: ["red", "black", "green"],
    },
    {
      id:"3",
      name: "Zeet Slim shirt",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/03/737152/1.jpg?1788",
        "https://img.joomcdn.net/d1b31b89ab87d5d18006c19fbddabaf73c5c23b9_original.jpeg",
        "https://www.rei.com/media/product/163975",
      ],

      description: "good Zeet Slim shirt",
      slug: "zeet-slim-shirt",
      price: 190,
      rating: 4.5,
      category: "Pants ",
      brand: "Zeet",
      numReviews: 10,
      countInStock: 18,
      colors: ["red", "black", "green"],
    },
    {
      id:"4",
      name: "Puma Slim shirt",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/48/432742/1.jpg?0863",
        "https://api.reveri.io/api/image/9b6d76c2-1f78-4393-9cdc-3b27b291f2b7",
        "https://www.rei.com/media/product/163975",
      ],

      description: "high Puma Slim shirt",
      slug: "puma-slim-shirt",
      price: 290,
      rating: 4.0,
      category: "Pants",
      brand: "Puma",
      numReviews: 12,
      countInStock: 13,
      colors: ["red", "black", "green"],
    },
    {
      id:"5",
      name: "Lacoste Slim shirt",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/48/432742/1.jpg?0863",
        "https://api.reveri.io/api/image/9b6d76c2-1f78-4393-9cdc-3b27b291f2b7",
        "https://www.rei.com/media/product/163975",
      ],

      description: "high Lacosta Slim shirt",
      slug: "puma-slim-shirt",
      price: 230,
      rating: 4.6,
      category: "Pants",
      brand: "Lacoste",
      numReviews: 10,
      countInStock: 0,
      colors: ["red", "black", "green"],
    },
    {
      id:"6",
      name: "Shee Slim shirt",
      img: [
        "https://eg.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/48/432742/1.jpg?0863",
        "https://api.reveri.io/api/image/9b6d76c2-1f78-4393-9cdc-3b27b291f2b7",
        "https://www.rei.com/media/product/163975",
      ],

      description: "high Lacosta Slim shirt",
      slug: "Shee shirt",
      price: 200,
      rating: 4.1,
      category: "shirt",
      brand: "Shee",
      numReviews: 6,
      countInStock: 5,
      colors: ["red", "black", "green"],
    },
  ],
};
export default data;
